lettucecfd/lettuce

- lettuce/collision.py
- lettuce/io.py
- lettuce/lattices.py
- lettuce/simulation.py
- lettuce/unit.py
- tests/test_collision.py
- tests/test_io.py
Supporting both AoS and SoA
EnergyReporter added for kinetic energy evaluation
> KBC Collision model v2

- .travis.yml
- lettuce/cli.py
- lettuce/collision.py
- lettuce/equilibrium.py
- lettuce/lattices.py
- lettuce/moments.py
- lettuce/streaming.py
- tests/conftest.py
- tests/test_flows.py
- tests/test_simulation.py
This is the first step. Next would be to remove the field stuff etc.
> removed LatticeAoS

- lettuce/collision.py
- tests/test_collision.py
Added a quite pythonic regularized LBM collision model for all dimensions
> Regularized lbm

- README.rst
- lettuce/cli.py
2 small fixes in terms of typo in README and cli.py
> Fix typo in README and cli.py

- lettuce/collision.py
- tests/test_collision.py
> Added KBC2D, Smagorinsky LES

- lettuce/io.py
- tests/test_io.py
> Generic reporters for mass, enstrophy, energy

- lettuce/flows/__init__.py
- lettuce/flows/couette.py
- lettuce/flows/doublyshear.py
- tests/test_flows.py
Hi, I am a student assistant working with DominikWilde. I did a thing:
Added Doublyperiodic shear layer as new test case in a new file, also added new file to __init__.py
> Shear layer

- lettuce/io.py
- lettuce/lattices.py
- lettuce/unit.py
- tests/test_io.py
- tests/test_unit.py
Everything that is reported should be in physical units!
@McBs 
please check if this looks correct.
@dominikwilde 
Please have a look, since it may break some of your stuff with Alex downstream.
> fix units in reporters

- lettuce/flows/couette.py
- lettuce/flows/doublyshear.py
- lettuce/flows/taylorgreen.py
- tests/test_simulation.py
- tests/test_util.py
this fixes #32 and a bug in the pressure field of the 3D TGV
> meshgrid indexing, TGV3D bugfix

- lettuce/boundary.py
- lettuce/flows/obstacle.py
- lettuce/simulation.py
- lettuce/streaming.py
- tests/test_boundaries.py
This PR changes the way masks are applied.
It allows boundary conditions to define `make_no_stream_mask` and `make_no_collision_mask` functions.
@MartinKliemank
> No-streaming Mask

- lettuce/observables.py
- lettuce/simulation.py
> Fix CUDA Tests

- lettuce/flows/doublyshear.py
> fix initial solution for doubly periodic shear layer

- .gitignore
> don't ignore docs Makefile and make.bat

- README.rst
This PR adds resources to the Readme (docs and CFDML2021 data)
> add resources to readme (docs and CFDML2021 data)

- HISTORY.rst
Let's get a minor release in before we merge the PRs with wide-ranging consequences (#78 #104 #53)
> Draft Release 0.2.2

- README.rst
- remove link to Zenodo DOI in favor of a "please cite" statement
- change CI badge from travis to github actions
- Link + bibtex to Springer chapter
> add paper to readme

- lettuce/collision.py
- lettuce/lattices.py
- lettuce/simulation.py
- tests/test_force.py
Follow-up PR to #104 with fixed tests. See discussion in there.
> Fix order of operations and velocity in forcing scheme

- lettuce/reporters.py
- tests/test_reporters.py
This PR fixes issue #52 and removes deprecated reporter classes.
> Remove deprecated reporters

- .github/workflows/lint.yml
- requirements.txt
- setup.py
Updated setup.py, requirements, and lint.yml for enhanced project setup, dependency management, and linting workflow.
> Updated requirements 

- README.rst
> README Enhancement: Update installation instructions

- .github/workflows/CI.yml
- requirements.txt
- setup.py
Fix current error of NumPy 2.0.0 integration for different library dependencies.
> Ci patch numpy2.0.0 error

- .github/workflows/CI.yml
> run tests weekly

- .github/workflows/CI.yml
> run CI on any pull request

- requirements.txt
- setup.py
Update matplotlib version in setup.py and requirements
- Set matplotlib version to 3.9.0 instead of 3.9.1 due to CI issues
> Patch requirements matplotlib

- requirements.txt
- setup.py
* Update requirements.txt
Patch: Fix CI Error with Matplotlib 3.9.1 in Requirements. Change it to 3.9
* Update setup.py
Update matplotlib version in setup.py
- Set matplotlib version to 3.9.0 instead of 3.9.1 due to CI issues
> Patch requirements matplotlib (#204)

- lettuce/ext/_flows/poiseuille.py
- tests/test_checkpoint.py
> added a test for dump and load

- lettuce/_flow.py
This approach ensures backward compatibility and gives users time to update their code. The deprecation warning directs users to use `torch.einsum` directly, helping them transition away from the custom implementation.
Later, flow.einsum can be removed in the future
> Deprecate custom `einsum` method in favor of `torch.einsum`

- examples/simple_flows/LambOseenVortex.py
- lettuce/ext/_flows/__init__.py
- lettuce/ext/_flows/_flow_by_name.py
- lettuce/ext/_flows/lamboseenvortex.py
This PR introduces a new LambOseenVortex2D external flow class. It provides initial conditions for simulating a 2D Lamb-Oseen vortex
> Add Lamb Oseen Vortex Flow in 2D
